In [29]:
import pandas as pd
articles_df = pd.read_csv("../data/Articles.csv", encoding="latin1")
articles_df.head()

,Article,Date,Heading,NewsType
0,KARACHI: The Sindh government has decided to b...,1/1/2015,sindh govt decides to cut public transport far...,business
1,HONG KONG: Asian markets started 2015 on an up...,1/2/2015,asia stocks up in new year trad,business
2,HONG KONG: Hong Kong shares opened 0.66 perce...,1/5/2015,hong kong stocks open 0.66 percent lower,business
3,HONG KONG: Asian markets tumbled Tuesday follo...,1/6/2015,asian stocks sink euro near nine year,business
4,NEW YORK: US oil prices Monday slipped below $...,1/6/2015,us oil prices slip below 50 a barr,business

In [2]:
import string

def preprocess(text):
    text = text.lower()
    text_no_punc = text.translate(str.maketrans('', '', string.punctuation))
    words = text_no_punc.split()
    return " ".join(words)

In [3]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
stoplist =set(nltk.corpus.stopwords.words('english'))

In [5]:
processed_docs = []

for text in df["Article"]:
    sentence = text.split()         
    filtered_words = []
    
    for word in sentence:
        if word.lower() not in stoplist:
            filtered_words.append(word)
    
    processed_docs.append(" ".join(filtered_words))

In [6]:
print("original:", sentence)
print("processed:", filtered_words)

original: ['strong>KARACHI:', 'Karachi-based', 'technology', 'incubator,', 'The', 'Nest', 'I/O', 'organized', '\x91Startup', 'Weekend\x92', 'to', 'bring', 'together', 'entrepreneurs', 'and', 'industry', 'leaders', 'to', 'collaborate', 'on', 'ideas,', 'polish', 'them', 'and', 'take', 'them', 'to', 'the', 'next', 'level.</strongGoogle-powered', '\x91Startup', 'Weekend\x92', 'event', 'is', 'a', 'global', 'campaign,', 'which', 'is', 'organized', 'in', 'over', '150', 'cities', 'all', 'over', 'the', 'world.', 'In', 'Karachi,', 'it', 'was', 'held', 'from', '24th', 'to', '26th', 'March.The', '54-hour', 'event', 'brought', 'together', 'local', 'entrepreneurs', 'and', 'industry', 'leaders', 'to', 'collaborate', 'on', 'ideas,', 'form', 'teams,', 'and', 'pitch', 'in', 'front', 'of', 'a', 'panel', 'of', 'judges.', 'This', 'year', 'more', 'than', '80', 'attendees', 'came', 'together', 'to', 'form', '27', 'teams,', 'and', 'worked', 'on', '60+', 'ideas', 'ranging', 'across', 'a', 'diverse', 'mix', 'of', 'fields.During', 'this', 'period', 'all', 'teams', 'were', 'coached', 'and', 'mentored', 'by', 'a', 'number', 'of', 'experts,', 'carefully', 'chosen', 'by', 'local', 'organizers', 'to', 'make', 'sure', 'that', 'all', 'teams', 'made', 'the', 'best', 'product', 'pitches', 'possible.After', 'four', 'marathon', 'sessions', 'of', 'pitching,', 'team', 'formation,', 'building', 'and', 'presentation,', 'the', 'judges', 'announced', 'the', 'winners.The', 'winner', 'of', 'the', 'event', 'was', '\x91Mirror', 'Magician\x92,', 'a', 'mirror', 'that', 'would', 'take', 'a', 'picture', 'using', 'augmented', 'reality', 'and', 'picture', 'automation,', 'while', 'the', 'runner', 'up', 'was', '\x91TrashIt\x92,', 'a', 'composting', 'bin', 'which', 'enables', 'people', 'to', 'dispose', 'off', 'their', 'trash', 'more', 'efficiently.The', 'second', 'runner', 'up', 'was', '\x91Gardener\x92,', 'an', 'online', 'gardening', 'service,', 'which', 'provides', 'gardening', 'services', 'through', 'an', 'App.img', 'alt=""', 'class="full-image"', 'src="https://www.thenews.com.pk/assets/front/tiny_mce/source/17425921_1295297090519477_8245902622336077088_n.jpg"/A', 'special', 'mention', 'was', 'also', 'given', 'to', '\x91Auctee\x92,', 'a', 'real-time', 'auctioning', 'service', 'through', 'secure', 'accounts', 'and', '\x91Champion', 'Mango\x92,', 'a', 'service', 'offering', 'premium', 'mangos', 'with', 'great', 'packaging', 'through', 'a', 'variety', 'of', 'distribution', 'channels.Daniyal', 'Zuberi,', 'the', 'brain', 'behind', 'Mirror', 'Magican,', 'was', 'excited', 'on', 'winning', 'the', '\x91amazing\x92', 'competition.', 'It', 'was', 'a', 'wonderful', '3-day', 'journey', 'that', 'started', 'with', 'my', 'idea', 'being', 'rejected', 'and', 'ended', 'up', 'by', 'stealing', 'the', 'show,', 'he', 'said.The', 'three', 'winning', 'teams', 'were', 'given', 'trophies,', 'while', 'all', 'attendees', 'got', 'participation', 'certificates.', 'dir="ltr"', 'lang="en">Cool', 'characters', 'in', 'the', 'gardener', 'app', 'pitch', '<a', 'href="https://twitter.com/hashtag/thenestio?src=hash">#thenestio</a>', '<a', 'href="https://twitter.com/hashtag/swkhi17?src=hash">#swkhi17</a>', '<a', 'href="https://twitter.com/hashtag/startupweekend?src=hash">#startupweekend</a>', '<a', 'href="https://t.co/HYy3i4fasF">pic.twitter.com/HYy3i4fasF</aIt', 'was', 'fantastic', 'event,', 'here', 'we', 'learned', 'the', 'art', 'of', 'realizing', 'our', 'dreams,', 'said', 'Muhammad', 'Samad,', 'the', 'co-founder', 'of', 'the', 'winning', 'idea.Sharing', 'her', 'excitement', 'on', 'the', 'successful', 'programme,', 'Jehan', 'Ara,', 'The', 'Big', 'Bird', 'at', 'the', 'Nest', 'I/O,', 'told', 'The', 'News', '\x91our', 'mission', 'is', 'to', 'empower', 'the', 'next', 'generation', 'of', 'entrepreneurs', 'in', 'Pakistan\x92.img', 'alt=""', 'src="https://www.thenews.com.pk/assets/front/tiny_mce/source/17498484_1295293073853212_6040510996268407073_n.jpg"/The', 'panel', 'of', 'judges', 'comprising', 'industry', 'leaders,', 'include', 'Yusuf', 'Jan,', 'Co-Founder', 'of', 'Dotzero;', 'Badar', 'Khushnood,', 'partner', 'at', 'Bramerz;', 'Faizan', 'Siddiqi,', 'Managing', 'Director', 'Interlink', 'Multi', 'Media,', 'a', 'technology', 'services', 'company', 'of', 'the', 'Jang', 'Media', 'Group;', 'Rabia', 'Garib', ',', 'Co-Founder', '&amp;', 'Chief', 'Editor', 'at', 'TheNewSpaces;', 'Midhat', 'Fatima,', 'Director', 'at', 'TEXT;', 'Raza', 'Matin,', 'Marketing', '&amp;', 'Business', 'Consultant', '-', 'Pakistan', 'at', 'Google;', 'and', 'Talha', 'Izhar,', 'Co-Founder', '&amp;', 'COO', 'at', 'Bakeware.The', 'judges', 'seemed', 'contented', 'with', 'the', 'level', 'of', 'participation', 'and', 'the', 'outcome.', 'Yusuf', 'Jan', 'said,', "I'd", 'say', 'if', 'every', 'weekend', 'was', 'a', "'Startup", "Weekend',", 'youthful', 'energy', 'and', 'passion', 'to', 'innovate', 'and', 'break', 'all', 'barriers', 'and', 'succeed\x92.Jehan', 'Ara', 'thanked', 'the', 'partners', 'for', 'supporting', 'the', 'event.', 'We', 'are', 'fortunate', 'to', 'have', 'the', 'support', 'of', 'strong', 'technology', 'partners', 'like', '\x91Google', 'for', 'entrepreneurs\x92', 'whose', 'mission', 'aligns', 'with', 'ours,', 'she', 'added.', '<link', 'href="https://www.thenews.com.pk//assets/front/css/photoswipe.css"', 'rel="stylesheet"/>', '<link', 'href="https://www.thenews.com.pk//assets/front/css/default-skin/default-skin.css"', 'rel="stylesheet"/>', '<link', 'href="https://www.thenews.com.pk//assets/front/css/site.css"', 'rel="stylesheet"/>', '<script', 'src="https://www.thenews.com.pk//assets/front/js/photoswipe.min.js"></script>', '<script', 'src="https://www.thenews.com.pk//assets/front/js/photoswipe-ui-default.min.js"></script>']
processed: ['strong>KARACHI:', 'Karachi-based', 'technology', 'incubator,', 'Nest', 'I/O', 'organized', '\x91Startup', 'Weekend\x92', 'bring', 'together', 'entrepreneurs', 'industry', 'leaders', 'collaborate', 'ideas,', 'polish', 'take', 'next', 'level.</strongGoogle-powered', '\x91Startup', 'Weekend\x92', 'event', 'global', 'campaign,', 'organized', '150', 'cities', 'world.', 'Karachi,', 'held', '24th', '26th', 'March.The', '54-hour', 'event', 'brought', 'together', 'local', 'entrepreneurs', 'industry', 'leaders', 'collaborate', 'ideas,', 'form', 'teams,', 'pitch', 'front', 'panel', 'judges.', 'year', '80', 'attendees', 'came', 'together', 'form', '27', 'teams,', 'worked', '60+', 'ideas', 'ranging', 'across', 'diverse', 'mix', 'fields.During', 'period', 'teams', 'coached', 'mentored', 'number', 'experts,', 'carefully', 'chosen', 'local', 'organizers', 'make', 'sure', 'teams', 'made', 'best', 'product', 'pitches', 'possible.After', 'four', 'marathon', 'sessions', 'pitching,', 'team', 'formation,', 'building', 'presentation,', 'judges', 'announced', 'winners.The', 'winner', 'event', '\x91Mirror', 'Magician\x92,', 'mirror', 'would', 'take', 'picture', 'using', 'augmented', 'reality', 'picture', 'automation,', 'runner', '\x91TrashIt\x92,', 'composting', 'bin', 'enables', 'people', 'dispose', 'trash', 'efficiently.The', 'second', 'runner', '\x91Gardener\x92,', 'online', 'gardening', 'service,', 'provides', 'gardening', 'services', 'App.img', 'alt=""', 'class="full-image"', 'src="https://www.thenews.com.pk/assets/front/tiny_mce/source/17425921_1295297090519477_8245902622336077088_n.jpg"/A', 'special', 'mention', 'also', 'given', '\x91Auctee\x92,', 'real-time', 'auctioning', 'service', 'secure', 'accounts', '\x91Champion', 'Mango\x92,', 'service', 'offering', 'premium', 'mangos', 'great', 'packaging', 'variety', 'distribution', 'channels.Daniyal', 'Zuberi,', 'brain', 'behind', 'Mirror', 'Magican,', 'excited', 'winning', '\x91amazing\x92', 'competition.', 'wonderful', '3-day', 'journey', 'started', 'idea', 'rejected', 'ended', 'stealing', 'show,', 'said.The', 'three', 'winning', 'teams', 'given', 'trophies,', 'attendees', 'got', 'participation', 'certificates.', 'dir="ltr"', 'lang="en">Cool', 'characters', 'gardener', 'app', 'pitch', '<a', 'href="https://twitter.com/hashtag/thenestio?src=hash">#thenestio</a>', '<a', 'href="https://twitter.com/hashtag/swkhi17?src=hash">#swkhi17</a>', '<a', 'href="https://twitter.com/hashtag/startupweekend?src=hash">#startupweekend</a>', '<a', 'href="https://t.co/HYy3i4fasF">pic.twitter.com/HYy3i4fasF</aIt', 'fantastic', 'event,', 'learned', 'art', 'realizing', 'dreams,', 'said', 'Muhammad', 'Samad,', 'co-founder', 'winning', 'idea.Sharing', 'excitement', 'successful', 'programme,', 'Jehan', 'Ara,', 'Big', 'Bird', 'Nest', 'I/O,', 'told', 'News', '\x91our', 'mission', 'empower', 'next', 'generation', 'entrepreneurs', 'Pakistan\x92.img', 'alt=""', 'src="https://www.thenews.com.pk/assets/front/tiny_mce/source/17498484_1295293073853212_6040510996268407073_n.jpg"/The', 'panel', 'judges', 'comprising', 'industry', 'leaders,', 'include', 'Yusuf', 'Jan,', 'Co-Founder', 'Dotzero;', 'Badar', 'Khushnood,', 'partner', 'Bramerz;', 'Faizan', 'Siddiqi,', 'Managing', 'Director', 'Interlink', 'Multi', 'Media,', 'technology', 'services', 'company', 'Jang', 'Media', 'Group;', 'Rabia', 'Garib', ',', 'Co-Founder', '&amp;', 'Chief', 'Editor', 'TheNewSpaces;', 'Midhat', 'Fatima,', 'Director', 'TEXT;', 'Raza', 'Matin,', 'Marketing', '&amp;', 'Business', 'Consultant', '-', 'Pakistan', 'Google;', 'Talha', 'Izhar,', 'Co-Founder', '&amp;', 'COO', 'Bakeware.The', 'judges', 'seemed', 'contented', 'level', 'participation', 'outcome.', 'Yusuf', 'Jan', 'said,', 'say', 'every', 'weekend', "'Startup", "Weekend',", 'youthful', 'energy', 'passion', 'innovate', 'break', 'barriers', 'succeed\x92.Jehan', 'Ara', 'thanked', 'partners', 'supporting', 'event.', 'fortunate', 'support', 'strong', 'technology', 'partners', 'like', '\x91Google', 'entrepreneurs\x92', 'whose', 'mission', 'aligns', 'ours,', 'added.', '<link', 'href="https://www.thenews.com.pk//assets/front/css/photoswipe.css"', 'rel="stylesheet"/>', '<link', 'href="https://www.thenews.com.pk//assets/front/css/default-skin/default-skin.css"', 'rel="stylesheet"/>', '<link', 'href="https://www.thenews.com.pk//assets/front/css/site.css"', 'rel="stylesheet"/>', '<script', 'src="https://www.thenews.com.pk//assets/front/js/photoswipe.min.js"></script>', '<script', 'src="https://www.thenews.com.pk//assets/front/js/photoswipe-ui-default.min.js"></script>']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(processed_docs)

print(X.shape)
print(vectorizer.get_feature_names_out()[:30])  

tfidf_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df.head()

(2692, 27602)
['00' '000' '0000' '000000' '0000ff' '000270' '000cc' '000m' '000mw'
 '000th' '001' '0011' '002' '0022' '0025' '002790' '0028' '0029' '003'
 '0032' '0035' '0037' '0038' '0040' '0041' '0043' '0045' '0046' '0047'
 '005']

,00,000,0000,000000,0000ff,000270,000cc,000m,000mw,000th,...,zulfiqar,zulqarnain,zuma,zurich,zusi,zverev,zvereva,zyl,étienne,über
0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.035448,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.026701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
X.toarray()[:5]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.03544789, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.02670082, 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(5, 27602))

In [ ]:
tfidf_df = pd.DataFrame(X.toarray(), columns=v.get_feature_names_out())
tfidf_df.head()
df = pd.read_csv("../data/Articles.csv", encoding="latin1")
df.head()

,Article,Date,Heading,NewsType
0,KARACHI: The Sindh government has decided to b...,1/1/2015,sindh govt decides to cut public transport far...,business
1,HONG KONG: Asian markets started 2015 on an up...,1/2/2015,asia stocks up in new year trad,business
2,HONG KONG: Hong Kong shares opened 0.66 perce...,1/5/2015,hong kong stocks open 0.66 percent lower,business
3,HONG KONG: Asian markets tumbled Tuesday follo...,1/6/2015,asian stocks sink euro near nine year,business
4,NEW YORK: US oil prices Monday slipped below $...,1/6/2015,us oil prices slip below 50 a barr,business

In [33]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def search(query, top_k=5):
    """
    TF–IDF + cosine similarity search.
    Returns top_k most relevant articles.
    """
    clean_query = preprocess(query)
    query_vec = vectorizer.transform([clean_query]) 
    similarities = cosine_similarity(query_vec, X)[0]  
    top_indices = np.argsort(similarities)[::-1][:top_k]
    results = []
    for rank, idx in enumerate(top_indices, start=1):
        results.append({
            "doc_id": int(idx),  
            "rank": rank,
            "score": float(similarities[idx]),
            "heading": articles_df.loc[idx, "Heading"],
            "date": articles_df.loc[idx, "Date"],
            "category": articles_df.loc[idx, "NewsType"],
            "snippet": str(articles_df.loc[idx, "Article"])[:250].replace("\n", " ")
        })
    return results

In [11]:
df.columns

Index(['Article', 'Date', 'Heading', 'NewsType'], dtype='object')

In [34]:
example_query = "stock market crash in asia"
results = search(example_query, top_k=5)
for r in results:
    print(f"Rank {r['rank']} | Score: {r['score']:.4f}")
    print(f"Heading : {r['heading']}")
    print(f"Date    : {r['date']} | Type: {r['category']}")
    print(f"Snippet : {r['snippet']}")
    print("-" * 90)

Rank 1 | Score: 0.1931
Heading : bullish kse jumps over 33000 psychological barrier
Date    : 1/9/2015 | Type: business
Snippet : KARACHI: Strong bulls on Friday pulled the benchmark KSE-100 Index at Karachi Stock Exchange (KSE) and taking it across the psychological barrier of 33,000 points with a single days gain of 207 points.The investors remained active right from the ope
------------------------------------------------------------------------------------------
Rank 2 | Score: 0.1910
Heading : US Ambassador rings trading bell Stock Exchang
Date    : 7/26/2016 | Type: business
Snippet : strong>KARACHI: American Ambassador David Hale visited Pakistan Stock Exchange in Karachi on Tuesday and rings the bell to open the trading.</strongAccording to the U.S. Census Bureau, in 2015, the United States was Pakistans largest bilateral expor
------------------------------------------------------------------------------------------
Rank 3 | Score: 0.1812
Heading : oil prices rise on china gr
Date    : 7/10/2015 | Type: business
Snippet : London: Oil prices ended the week firmer Friday, lifted by a recovery in share prices in China, which is the world´s biggest consumer of energy and major buyer of commodities generally.The crude market won a boost also from surging European stock mar
------------------------------------------------------------------------------------------
Rank 4 | Score: 0.1603
Heading : Pakistan shares higher best weekly gai
Date    : 6/17/2016 | Type: business
Snippet : strong>KARACHI: Pakistan stocks hit a fresh record closing high on Friday, led by energy and bank shares, with the main index posting its best weekly gain in nearly three years after the country´s stock market was included in MSCI´s key benchmark ear
------------------------------------------------------------------------------------------
Rank 5 | Score: 0.1516
Heading : Ishaq Dar formally launches Pakistan Stock Exchang
Date    : 1/11/2016 | Type: business
Snippet : strong>ISLAMABAD: Pakistan stock Exchange (PSX) has been formally launched after integration of all the three bourses of the country.</strongMinister for Finance Ishaq Dar on Monday inaugurated the PSX, formed after the integration of Karachi, Lahore
------------------------------------------------------------------------------------------

In [35]:
from rank_bm25 import BM25Okapi
import string

def remove_puncts(input_string):
    return input_string.translate(str.maketrans('', '', string.punctuation)).lower()

original_corpus = articles_df["Article"].astype(str).tolist()
cleaned_corpus = [remove_puncts(doc) for doc in original_corpus]
tokenized_corpus = [doc.split() for doc in cleaned_corpus]

bm25 = BM25Okapi(tokenized_corpus)
tokenized_corpus[:2]

[['karachi',
  'the',
  'sindh',
  'government',
  'has',
  'decided',
  'to',
  'bring',
  'down',
  'public',
  'transport',
  'fares',
  'by',
  '7',
  'per',
  'cent',
  'due',
  'to',
  'massive',
  'reduction',
  'in',
  'petroleum',
  'product',
  'prices',
  'by',
  'the',
  'federal',
  'government',
  'geo',
  'news',
  'reportedsources',
  'said',
  'reduction',
  'in',
  'fares',
  'will',
  'be',
  'applicable',
  'on',
  'public',
  'transport',
  'rickshaw',
  'taxi',
  'and',
  'other',
  'means',
  'of',
  'travelingmeanwhile',
  'karachi',
  'transport',
  'ittehad',
  'kti',
  'has',
  'refused',
  'to',
  'abide',
  'by',
  'the',
  'government',
  'decisionkti',
  'president',
  'irshad',
  'bukhari',
  'said',
  'the',
  'commuters',
  'are',
  'charged',
  'the',
  'lowest',
  'fares',
  'in',
  'karachi',
  'as',
  'compare',
  'to',
  'other',
  'parts',
  'of',
  'the',
  'country',
  'adding',
  'that',
  '80pc',
  'vehicles',
  'run',
  'on',
  'compressed',
  'natural',
  'gas',
  'cng',
  'bukhari',
  'said',
  'karachi',
  'transporters',
  'will',
  'cut',
  'fares',
  'when',
  'decrease',
  'in',
  'cng',
  'prices',
  'will',
  'be',
  'made'],
 ['hong',
  'kong',
  'asian',
  'markets',
  'started',
  '2015',
  'on',
  'an',
  'upswing',
  'in',
  'limited',
  'trading',
  'on',
  'friday',
  'with',
  'mainland',
  'chinese',
  'stocks',
  'surging',
  'in',
  'hong',
  'kong',
  'on',
  'speculation',
  'beijing',
  'may',
  'ease',
  'monetary',
  'policy',
  'to',
  'boost',
  'slowing',
  'growthhong',
  'kong',
  'rose',
  '107',
  'percent',
  'closing',
  '25278',
  'points',
  'higher',
  'at',
  '2385782seoul',
  'closed',
  'up',
  '057',
  'percent',
  'rising',
  '1085',
  'points',
  'to',
  '192644',
  'while',
  'sydney',
  'gained',
  '046',
  'percent',
  'or',
  '2489',
  'points',
  'to',
  'close',
  'at',
  '54359singapore',
  'edged',
  'up',
  '019',
  'percent',
  'gaining',
  '639',
  'points',
  'to',
  '337154markets',
  'in',
  'mainland',
  'china',
  'japan',
  'taiwan',
  'new',
  'zealand',
  'the',
  'philippines',
  'and',
  'thailand',
  'remained',
  'closed',
  'for',
  'holidayswith',
  'mainland',
  'bourses',
  'shut',
  'until',
  'january',
  '5',
  'shares',
  'in',
  'chinese',
  'developers',
  'and',
  'financial',
  'companies',
  'surged',
  'in',
  'hong',
  'kong',
  'stoked',
  'by',
  'hopes',
  'that',
  'beijing',
  'could',
  'ease',
  'monetary',
  'policy',
  'to',
  'support',
  'lagging',
  'growth',
  'in',
  'the',
  'world´s',
  'secondlargest',
  'economychina',
  'vanke',
  'the',
  'country´s',
  'biggest',
  'developer',
  'by',
  'sales',
  'leapt',
  '108',
  'percent',
  'and',
  'the',
  'people´s',
  'insurance',
  'company',
  'group',
  'of',
  'china',
  'ltd',
  'was',
  'up',
  '551',
  'percent',
  'in',
  'afternoon',
  'tradingtrainbuilders',
  'csr',
  'corp',
  'and',
  'china',
  'cnr',
  'corp',
  'soared',
  'csr',
  'by',
  '165',
  'percent',
  'and',
  'china',
  'cnr',
  'by',
  '160',
  'percent',
  'extending',
  'gains',
  'on',
  'december',
  '31',
  'after',
  'they',
  'announced',
  'a',
  'merger',
  'agreementchina´s',
  'manufacturing',
  'growth',
  'dropped',
  'in',
  'december',
  'to',
  'its',
  'lowest',
  'level',
  'of',
  '2014',
  'an',
  'official',
  'survey',
  'showed',
  'thursday',
  'as',
  'the',
  'sector',
  'struggles',
  'with',
  'weak',
  'domestic',
  'demandchina´s',
  'official',
  'purchasing',
  'managers´',
  'index',
  'pmi',
  'released',
  'by',
  'the',
  'national',
  'bureau',
  'of',
  'statistics',
  'nbs',
  'came',
  'in',
  'at',
  '501',
  'last',
  'month',
  'down',
  'from',
  '503',
  'recorded',
  'in',
  'novemberthe',
  'index',
  'which',
  'tracks',
  'activity',
  'in',
  'factories',
  'and',
  'workshops',
  'is',
  'considered',
  'a',
  'key',
  'indicator',
  'of',
  'the',
  'health',
  'of',
  'china´s',
  'economy',
  'a',
  'major',
  'driver',
  'of',
  'global',
  'growth',
  'a',
  'figure',
  'above',
  '50',
  'signals',
  'expansion',
  'while',
  'anything',
  'below',
  'indicates',
  'contractiongrowth',
  'momentum',
  'is',
  'still',
  'insufficient',
  'nbs',
  'said',
  'in',
  'a',
  'statement',
  'investors',
  'eye',
  'us',
  'factory',
  'data',
  'on',
  'forex',
  'markets',
  'the',
  'dollar',
  'extended',
  'gains',
  'ahead',
  'of',
  'the',
  'release',
  'of',
  'american',
  'factory',
  'data',
  'due',
  'later',
  'on',
  'friday',
  'and',
  'following',
  'a',
  'steady',
  'stream',
  'of',
  'good',
  'news',
  'from',
  'the',
  'world´s',
  'biggest',
  'economythe',
  'dollar',
  'bought',
  '12044',
  'yen',
  'compared',
  'to',
  '11944',
  'yen',
  'in',
  'final',
  '2014',
  'trading',
  'on',
  'wednesdaywall',
  'street',
  'toasted',
  'a',
  'banner',
  'year',
  'in',
  '2014',
  'with',
  'us',
  'equity',
  'markets',
  'finishing',
  'near',
  'alltime',
  'highsthe',
  'euro',
  'meanwhile',
  'slipped',
  'amid',
  'growing',
  'expectations',
  'that',
  'the',
  'european',
  'central',
  'bank',
  'which',
  'meets',
  'on',
  'january',
  '22',
  'will',
  'start',
  'buying',
  'sovereign',
  'bonds',
  'the',
  'single',
  'currency',
  'bought',
  '12061',
  'compared',
  'to',
  '12160',
  'in',
  'preholiday',
  'tradethe',
  'ecb',
  'has',
  'already',
  'used',
  'several',
  'tools',
  'to',
  'push',
  'inflation',
  'in',
  'member',
  'nations',
  'back',
  'up',
  'to',
  'the',
  '20',
  'percent',
  'annual',
  'rate',
  'it',
  'regards',
  'as',
  'healthy',
  'including',
  'asset',
  'purchases',
  'and',
  'making',
  'cheap',
  'loans',
  'available',
  'to',
  'banksit',
  'is',
  'also',
  'examining',
  'the',
  'possibility',
  'of',
  'largescale',
  'purchases',
  'of',
  'sovereign',
  'debt',
  'socalled',
  'quantitative',
  'easing',
  'qe',
  'to',
  'help',
  'jumpstart',
  'the',
  'european',
  'union´s',
  'moribund',
  'economyoil',
  'prices',
  'rose',
  'on',
  'friday',
  'with',
  'us',
  'benchmark',
  'west',
  'texas',
  'intermediate',
  'for',
  'february',
  'delivery',
  'rising',
  '44',
  'cents',
  'to',
  '5407',
  'and',
  'brent',
  'crude',
  'for',
  'february',
  'gaining',
  '18',
  'cents',
  'to',
  '5751the',
  'gains',
  'in',
  'asian',
  'trading',
  'are',
  'likely',
  'because',
  'of',
  'the',
  'positive',
  'us',
  'crude',
  'stockpiles',
  'data',
  'released',
  'on',
  'wednesday',
  'daniel',
  'ang',
  'investment',
  'analyst',
  'at',
  'phillip',
  'futures',
  'in',
  'singapore',
  'told',
  'afpus',
  'crude',
  'reserves',
  'fell',
  'by',
  '18',
  'million',
  'barrels',
  'in',
  'the',
  'week',
  'to',
  'december',
  '26',
  'the',
  'us',
  'energy',
  'information',
  'administration',
  'said',
  'in',
  'its',
  'last',
  'petroleum',
  'report',
  'for',
  '2014',
  'released',
  'on',
  'wednesday',
  'boosting',
  'prices',
  'that',
  'lost',
  'nearly',
  'half',
  'their',
  'value',
  'in',
  'the',
  'second',
  'half',
  'of',
  'the',
  'yearthere',
  'is',
  'growing',
  'speculation',
  'that',
  'the',
  'slide',
  'in',
  'global',
  'oil',
  'prices',
  'the',
  'biggest',
  'since',
  'the',
  'financial',
  'crisis',
  'in',
  '2008',
  'may',
  'have',
  'been',
  'excessiveif',
  'we',
  'do',
  'see',
  'some',
  'supplyside',
  'responses',
  'or',
  'even',
  'if',
  'they´re',
  'anticipated',
  'over',
  'the',
  'course',
  'of',
  'this',
  'first',
  'quarter',
  'of',
  'the',
  'year',
  'we',
  'might',
  'find',
  'that',
  'oil',
  'has',
  'in',
  'fact',
  'bottomed',
  'michael',
  'mccarthy',
  'a',
  'chief',
  'strategist',
  'at',
  'cmc',
  'markets',
  'in',
  'sydney',
  'told',
  'bloomberggold',
  'was',
  'at',
  '118236',
  'an',
  'ounce',
  'compared',
  'with',
  '119900',
  'in',
  'endofyear',
  'trading',
  'on',
  'wednesdayin',
  'other',
  'markets',
  'jakarta',
  'ended',
  'up',
  '030',
  'percent',
  'or',
  '1582',
  'points',
  'at',
  '524277coal',
  'firm',
  'indo',
  'tambangraya',
  'megah',
  'gained',
  '341',
  'percent',
  'to',
  '15900',
  'rupiah',
  'while',
  'miner',
  'aneka',
  'tambang',
  'slipped',
  '188',
  'percent',
  'to',
  '1045',
  'rupiah',
  'malaysia´s',
  'main',
  'stock',
  'index',
  'shed',
  '048',
  'percent',
  'or',
  '848',
  'points',
  'to',
  'close',
  'at',
  '175277malayan',
  'banking',
  'lost',
  '055',
  'percent',
  'to',
  '912',
  'ringgit',
  'public',
  'bank',
  'slipped',
  '044',
  'percent',
  'to',
  '1822',
  'while',
  'top',
  'globe',
  'added',
  '177',
  'percent',
  '460',
  'ringgit',
  'singapore',
  'rose',
  '016',
  'percent',
  'or',
  '544',
  'points',
  'to',
  '337059agribusiness',
  'company',
  'wilmar',
  'international',
  'gained',
  '093',
  'percent',
  'to',
  'sg327',
  'while',
  'real',
  'estate',
  'developer',
  'capitaland',
  'dipped',
  '030',
  'percent',
  'to',
  'sg330',
  'mumbai',
  'gained',
  '138',
  'percent',
  'or',
  '38036',
  'points',
  'to',
  'end',
  'at',
  '2788790housing',
  'development',
  'finance',
  'corp',
  'rose',
  '430',
  'percent',
  'to',
  '117180',
  'rupees',
  'while',
  'mahindra',
  'mahindra',
  'fell',
  '092',
  'percent',
  'to',
  '122480',
  'rupees',
  'afp']]

In [ ]:
import numpy as np

def search_bm25(query, k=5):
    q_tokens = preprocess(query).split()
    scores = bm25.get_scores(q_tokens)
    top_idx = np.argsort(scores)[::-1][:k]

    results = []
    for i, idx in enumerate(top_idx):
        results.append({
            "doc_id": int(idx),  # evaluation
            "rank": i + 1,
            "score": float(scores[idx]),
            "heading": articles_df.loc[idx, "Heading"],
            "date": articles_df.loc[idx, "Date"],
            "category": articles_df.loc[idx, "NewsType"],
            "snippet": str(articles_df.loc[idx, "Article"])[:250].replace("\n", " ")
        })
    return results

In [38]:
example_query = "stock market crash in asia"

results_tfidf = search(example_query, top_k=5)

for r in results_tfidf:
    print(f"Rank {r['rank']} | Score: {r['score']:.4f}")
    print(f"Heading : {r['heading']}")
    print(f"Date    : {r['date']} | Type: {r['category']}")
    print(f"Snippet : {r['snippet']}")
    print("-" * 90)

Rank 1 | Score: 0.1931
Heading : bullish kse jumps over 33000 psychological barrier
Date    : 1/9/2015 | Type: business
Snippet : KARACHI: Strong bulls on Friday pulled the benchmark KSE-100 Index at Karachi Stock Exchange (KSE) and taking it across the psychological barrier of 33,000 points with a single days gain of 207 points.The investors remained active right from the ope
------------------------------------------------------------------------------------------
Rank 2 | Score: 0.1910
Heading : US Ambassador rings trading bell Stock Exchang
Date    : 7/26/2016 | Type: business
Snippet : strong>KARACHI: American Ambassador David Hale visited Pakistan Stock Exchange in Karachi on Tuesday and rings the bell to open the trading.</strongAccording to the U.S. Census Bureau, in 2015, the United States was Pakistans largest bilateral expor
------------------------------------------------------------------------------------------
Rank 3 | Score: 0.1812
Heading : oil prices rise on china gr
Date    : 7/10/2015 | Type: business
Snippet : London: Oil prices ended the week firmer Friday, lifted by a recovery in share prices in China, which is the world´s biggest consumer of energy and major buyer of commodities generally.The crude market won a boost also from surging European stock mar
------------------------------------------------------------------------------------------
Rank 4 | Score: 0.1603
Heading : Pakistan shares higher best weekly gai
Date    : 6/17/2016 | Type: business
Snippet : strong>KARACHI: Pakistan stocks hit a fresh record closing high on Friday, led by energy and bank shares, with the main index posting its best weekly gain in nearly three years after the country´s stock market was included in MSCI´s key benchmark ear
------------------------------------------------------------------------------------------
Rank 5 | Score: 0.1516
Heading : Ishaq Dar formally launches Pakistan Stock Exchang
Date    : 1/11/2016 | Type: business
Snippet : strong>ISLAMABAD: Pakistan stock Exchange (PSX) has been formally launched after integration of all the three bourses of the country.</strongMinister for Finance Ishaq Dar on Monday inaugurated the PSX, formed after the integration of Karachi, Lahore
------------------------------------------------------------------------------------------

In [39]:
results_bm25 = search_bm25(example_query, k=5)

for r in results_bm25:
    print(f"Rank {r['rank']} | BM25 Score: {r['score']:.4f}")
    print(f"Heading : {r['heading']}")
    print(f"Date    : {r['date']} | Type: {r['category']}")
    print(f"Snippet : {r['snippet']}")
    print("-" * 90)

Rank 1 | BM25 Score: 13.4178
Heading : kse down 1419 points at closing
Date    : 8/24/2015 | Type: business
Snippet : KARACHI: Following Asian stock market trend, Karachi Stock Exchange (KSE) shed over 1,419 points at the closing of Monday's trading.With over 1,400 points down, the KSE-100 index was recorded at 33,100.The KSE witnessed a three month low and market c
------------------------------------------------------------------------------------------
Rank 2 | BM25 Score: 13.2071
Heading : PCB Chairman Shahryar Khan decides to step d
Date    : 4/1/2016 | Type: sports
Snippet : strong>LAHORE: Pakistan Cricket Board (PCB) Chairman Shahryar Khan has decided to resign following team's poor performance in World Twenty20 and Asia Cup, sources said.</strongSources said that PCB chairman will announce his decision in a press confe
------------------------------------------------------------------------------------------
Rank 3 | BM25 Score: 12.1112
Heading : PCB chairman denies resignation rumour
Date    : 4/1/2016 | Type: sports
Snippet : LAHORE: Pakistan Cricket Board (PCB) Chairman Shahryar Khan on Friday rejected reports that he has tendered resignation from his post for national teams dismal performance in World Twenty20 and Asia Cup.Speaking to media, he said: "I have not tender
------------------------------------------------------------------------------------------
Rank 4 | BM25 Score: 12.0456
Heading : bullish kse jumps over 33000 psychological barrier
Date    : 1/9/2015 | Type: business
Snippet : KARACHI: Strong bulls on Friday pulled the benchmark KSE-100 Index at Karachi Stock Exchange (KSE) and taking it across the psychological barrier of 33,000 points with a single days gain of 207 points.The investors remained active right from the ope
------------------------------------------------------------------------------------------
Rank 5 | BM25 Score: 11.7634
Heading : Pakistan shares higher best weekly gai
Date    : 6/17/2016 | Type: business
Snippet : strong>KARACHI: Pakistan stocks hit a fresh record closing high on Friday, led by energy and bank shares, with the main index posting its best weekly gain in nearly three years after the country´s stock market was included in MSCI´s key benchmark ear
------------------------------------------------------------------------------------------

In [47]:
search("stock market crash in asia", top_k=10)

[{'doc_id': 6,
  'rank': 1,
  'score': 0.19314209448655012,
  'heading': 'bullish kse jumps over 33000 psychological barrier',
  'date': '1/9/2015',
  'category': 'business',
  'snippet': 'KARACHI: Strong bulls on Friday pulled the benchmark KSE-100 Index at Karachi Stock Exchange (KSE) and taking it across the psychological barrier of 33,000 points with a single day\x92s gain of 207 points.The investors remained active right from the ope'},
 {'doc_id': 817,
  'rank': 2,
  'score': 0.1910193391894398,
  'heading': 'US Ambassador rings trading bell Stock Exchang',
  'date': '7/26/2016',
  'category': 'business',
  'snippet': 'strong>KARACHI: American Ambassador David Hale visited Pakistan Stock Exchange in Karachi on Tuesday and rings the bell to open the trading.</strongAccording to the U.S. Census Bureau, in 2015, the United States was Pakistan\x92s largest bilateral expor'},
 {'doc_id': 204,
  'rank': 3,
  'score': 0.18118238214278193,
  'heading': 'oil prices rise on china gr',
  'date': '7/10/2015',
  'category': 'business',
  'snippet': 'London: Oil prices ended the week firmer Friday, lifted by a recovery in share prices in China, which is the world´s biggest consumer of energy and major buyer of commodities generally.The crude market won a boost also from surging European stock mar'},
 {'doc_id': 726,
  'rank': 4,
  'score': 0.16029230044718487,
  'heading': 'Pakistan shares higher best weekly gai',
  'date': '6/17/2016',
  'category': 'business',
  'snippet': 'strong>KARACHI: Pakistan stocks hit a fresh record closing high on Friday, led by energy and bank shares, with the main index posting its best weekly gain in nearly three years after the country´s stock market was included in MSCI´s key benchmark ear'},
 {'doc_id': 428,
  'rank': 5,
  'score': 0.15164808686023853,
  'heading': 'Ishaq Dar formally launches Pakistan Stock Exchang',
  'date': '1/11/2016',
  'category': 'business',
  'snippet': 'strong>ISLAMABAD: Pakistan stock Exchange (PSX) has been formally launched after integration of all the three bourses of the country.</strongMinister for Finance Ishaq Dar on Monday inaugurated the PSX, formed after the integration of Karachi, Lahore'},
 {'doc_id': 253,
  'rank': 6,
  'score': 0.151025805228371,
  'heading': 'kse down 1419 points at closing',
  'date': '8/24/2015',
  'category': 'business',
  'snippet': "KARACHI: Following Asian stock market trend, Karachi Stock Exchange (KSE) shed over 1,419 points at the closing of Monday's trading.With over 1,400 points down, the KSE-100 index was recorded at 33,100.The KSE witnessed a three month low and market c"},
 {'doc_id': 2612,
  'rank': 7,
  'score': 0.14372696481793912,
  'heading': 'Pakistan Stock Exchange crosses 50000 points first time history',
  'date': '1/24/2017',
  'category': 'business',
  'snippet': 'strong>KARACHI: Pakistan Stock Exchange witnessed bullish trend on second consecutive day, on Tuesday at the start of the business as 100 index crossed the level of 50 thousand points with 174 points increase in hundred index.\xa0</strongThe market had '},
 {'doc_id': 2430,
  'rank': 8,
  'score': 0.14104614969088994,
  'heading': 'Pakistan Stock Exchange says Shanghai bourse interested in buying ',
  'date': '10/3/2016',
  'category': 'business',
  'snippet': 'strong>KARACHI: Pakistan Stock Exchange Ltd has received interest from international companies including the Shanghai Stock Exchange to buy a stake, the head of the Pakistani bourse said on Monday.</strongThe Pakistani bourse has been searching for a'},
 {'doc_id': 251,
  'rank': 9,
  'score': 0.1405228198964176,
  'heading': 'dollar reaches 17 month high against ru',
  'date': '8/24/2015',
  'category': 'business',
  'snippet': 'KARACHI: With stock markets in Asia tumbling including the Karachi Stock Exchange (KSE) the Pakistani rupee fell to its 17 month low against the US dollar.The dollar rose by RS2.03 in the interbank trading at Rs104 against the rupee. A spokesman for '},
 {'doc_id': 84,
  'rank': 10,
  'score': 0.13819061052357595,
  'heading': 'stocks tumble as kse 100 share index drops 817 poi',
  'date': '3/18/2015',
  'category': 'business',
  'snippet': 'KARACHI: Bearish spell at Karachi Stock Exchange (KSE) grew in strength on Wednesday, as the benchmark KSE 100-share Index witnessed a sharp decline of 817.28 points or 2.5 percent to close at 31,524.During the intra-day trading, the main Index at on'}]

In [46]:
search("covid vaccine rollout", top_k=10)

[{'doc_id': 582,
  'rank': 1,
  'score': 0.07697363121140961,
  'heading': 'Automakers fight for slice of Chinese eco car mar',
  'date': '4/26/2016',
  'category': 'business',
  'snippet': 'BEIJING: Automakers in China face a war of attrition in the market for environmentally friendly cars as tighter regulations force heavy spending on development and production while a slowing economy leaves the demand outlook hazy.Top vehicle manufact'},
 {'doc_id': 966,
  'rank': 2,
  'score': 0.05092062277157169,
  'heading': 'India Ambani telecoms venture free calls cut price d',
  'date': '9/2/2016',
  'category': 'business',
  'snippet': 'strong>MUMBAI: Reliance Industries unveiled its Jio telecom network on Thursday, touting free calls and rock-bottom data prices that sent shares of established telecom players into a nosedive on fears of an all-out price war.</strongReliance Chairman'},
 {'doc_id': 2691,
  'rank': 3,
  'score': 0.0,
  'heading': 'Google powered Startup Weekend energizing proud Pakistan driv',
  'date': '3/27/2017',
  'category': 'business',
  'snippet': 'strong>KARACHI: Karachi-based technology incubator, The Nest I/O organized \x91Startup Weekend\x92 to bring together entrepreneurs and industry leaders to collaborate on ideas, polish them and take them to the next level.</strongGoogle-powered \x91Startup Wee'},
 {'doc_id': 2690,
  'rank': 4,
  'score': 0.0,
  'heading': 'New Development Bank plans joint investments in economies along Belt Road',
  'date': '3/27/2017',
  'category': 'business',
  'snippet': 'strong>BEIJING: The New Development Bank plans to co-finance infrastructure projects with the Asian Infrastructure Investment Bank (AIIB) along the Belt and Road economies after more members join in, the NDB\x92s vice president said.</strong\x93There will '},
 {'doc_id': 15,
  'rank': 5,
  'score': 0.0,
  'heading': 'report presented to pm holds ogra responsible for fuel crisi',
  'date': '1/20/2015',
  'category': 'business',
  'snippet': 'ISLAMABAD: A two member committee tasked to probe the prevailing petrol shortage on Tuesday said that the situation was a serious failure on the part of OGRA (Oil and Gas Regulatory Authority) as a regulator. The committee presented its initial findi'},
 {'doc_id': 30,
  'rank': 6,
  'score': 0.0,
  'heading': 'oil prices slide after rally',
  'date': '2/4/2015',
  'category': 'business',
  'snippet': 'London: Global oil prices slid Wednesday following a three-day rally as dealers were divided on whether the commodity has bottomed out after a plunge of nearly 60 percent since June. US benchmark West Texas Intermediate (WTI) for delivery in March sh'},
 {'doc_id': 29,
  'rank': 7,
  'score': 0.0,
  'heading': 'us probes moodys rating agency',
  'date': '2/2/2015',
  'category': 'business',
  'snippet': "NEW YORK: US authorities are investigating the credit rating agency Moody's over its glowing assessments of mortgage deals in the runup to the 2008 financial crisis, The Wall Street Journal reported Sunday.Citing people familiar with the situation, t"},
 {'doc_id': 28,
  'rank': 8,
  'score': 0.0,
  'heading': 'finance minister announces five percent increase in gst on pol produ',
  'date': '1/31/2015',
  'category': 'business',
  'snippet': 'ISLAMABAD:  Federal Minister for Finance Ishaq Dar on Saturday announced a five percent increase in the General Sales Tax (GST) on petroleum products.Dar said that the increment would enable a recovery of 12 billion rupees.The minister, however, went'},
 {'doc_id': 27,
  'rank': 9,
  'score': 0.0,
  'heading': 'oil slumps as us crude reserves surge to record hig',
  'date': '1/29/2015',
  'category': 'business',
  'snippet': 'New York: Oil tumbled to near a six-year low Wednesday as US crude stocks soared to a record high, sparking fresh fears over the growing global supply glut.US benchmark West Texas Intermediate (WTI) for March delivery dropped $1.78 to $44.45 a barrel'},
 {'doc_id': 26,
  'rank': 10,
  'score': 0.0,
  'heading': 'sbp warns islamic banks to be more equitab',
  'date': '1/29/2015',
  'category': 'business',
  'snippet': 'KARACHI: State Bank of Pakistan (SBP) governor on Thursday urged the country´s Islamic banks to develop ways to reward their customers in line with a surge in the sector´s profitability, or face regulatory action. Islamic finance is experiencing a re'}]

In [48]:
search("elections in pakistan", top_k=10)

[{'doc_id': 729,
  'rank': 1,
  'score': 0.11841151556813664,
  'heading': 'Pakistan on track to end power shortages within two year',
  'date': '6/20/2016',
  'category': 'business',
  'snippet': 'strong>Pakistan could end energy rationing within two years, the Asia Development Bank (ADB) country director for Pakistan said on Monday, adding weight to government claims that they will end frequent outages in time for the 2018 elections.</strongA'},
 {'doc_id': 2481,
  'rank': 2,
  'score': 0.10944866320109543,
  'heading': 'Gold slips firm dollar US election concerns lifting demand',
  'date': '11/4/2016',
  'category': 'business',
  'snippet': 'strong>BENGALURU: Gold eased on Friday as the dollar firmed ahead of U.S. jobs data, but looked set for a weekly gain of 2 percent, while investor appetite for the safe-haven asset stayed intact over signs of a close-run U.S. presidential election.</'},
 {'doc_id': 2511,
  'rank': 3,
  'score': 0.10748332598043059,
  'heading': 'Asian shares on the defensive as US yields dollar ri',
  'date': '11/21/2016',
  'category': 'business',
  'snippet': "strong>TOKYO: Asian shares were on the defensive on Monday, undermined by fears that the strength in the U.S. dollar and rising U.S. bond yields since Donald Trump's election to president could accelerate fund outflows from emerging markets.</strongM"},
 {'doc_id': 1441,
  'rank': 4,
  'score': 0.10163708675381876,
  'heading': 'Stats back Pakistan to avenge Asia Cup defeat against Banglad',
  'date': '3/16/2016',
  'category': 'sports',
  'snippet': 'By Faizan Lakhani\xa0strong>With a clear statistical edge over Bangladesh, Pakistan cricket team is set to launch its World T20 mission with the aim of improving their record against Bangladeshis on Wednesday.</strongThe current form may not be in Pakis'},
 {'doc_id': 731,
  'rank': 5,
  'score': 0.10021647926415056,
  'heading': 'rising economy Pakistan hampered image prob',
  'date': '6/20/2016',
  'category': 'business',
  'snippet': 'strong>KARACHI/ISLAMABAD: Pakistani stocks are soaring, improved security is fuelling economic growth and the South Asian nation will be upgraded to "emerging market" status by index provider MSCI.</strongBut for Ali Saigol, co-founder of a private e'},
 {'doc_id': 1251,
  'rank': 6,
  'score': 0.09880262442006012,
  'heading': 'Indian HC ensures VVIP security for Pakistan cricket ',
  'date': '2/17/2016',
  'category': 'sports',
  'snippet': 'Indian HC ensures VVIP security for Pakistan cricket teamLAHORE: Indian high commissioner Gautam Bambawale assured that the Pakistan cricket team would be provided the security higher than the President.He said that Indian prime minister Narendra Mod'},
 {'doc_id': 1122,
  'rank': 7,
  'score': 0.09371603243048168,
  'heading': 'Kiwis set 281 runs target for Pakistan in first ODI',
  'date': '1/25/2016',
  'category': 'sports',
  'snippet': 'strong>WELLINGTON: New Zealand defeated Pakistan by 70 runs in first one-day international of three-match series here on Monday.</strongBatting first, after Pakistan skipper Azhar Ali won the toss and decided to field, Kiwis set 281 runs target for t'},
 {'doc_id': 135,
  'rank': 8,
  'score': 0.09315790769110363,
  'heading': 'sp raises pakistans outlook forecasts higher gr',
  'date': '5/6/2015',
  'category': 'business',
  'snippet': "KARACHI: Standard and Poor's on Tuesday revised Pakistan's credit rating outlook from stable to positive and forecast higher GDP growth for 2015 to 2017, amid a stint of economic reforms.In a statement, the agency said the country had made significan"},
 {'doc_id': 2007,
  'rank': 9,
  'score': 0.08873199986981456,
  'heading': 'Misbah England series tests Pakistan cri',
  'date': '6/17/2016',
  'category': 'sports',
  'snippet': 'strong>LAHORE: Pakistan cricket captain Misbah-ul Haq hopes the upcoming test series in England will help spur the return of international cricket to the South Asian nation after a seven-year absence due to security fears.</strongPakistan has not sta'},
 {'doc_id': 89,
  'rank': 10,
  'score': 0.08801585791159283,
  'heading': 'moodys upgrades pakistan bond rating',
  'date': '3/25/2015',
  'category': 'business',
  'snippet': 'KARACHI: Moody\x92s upgraded Pakistan\x92s dollar bonds rating one notch from stable to positive on Wednesday on the back of the country\x92s improving macroeconomic indicators.The financial ratings firm said its decision came in view of Pakistan\x92s strengthen'}]

In [53]:
ground_truth = {
    "stock market crash in asia": [126],
    "covid vaccine rollout": [],
    "elections in pakistan": []
}
from sklearn.metrics import precision_score, recall_score, f1_score
evaluation_results = {}
for query, relevant_docs in ground_truth.items():
    results = search(query, top_k=10)
    retrieved_docs = [r["doc_id"] for r in results]
    
    y_true = [1 if doc_id in relevant_docs else 0 for doc_id in retrieved_docs]
    y_pred = [1] * len(retrieved_docs)  
    
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    
    evaluation_results[query] = {
        "precision": precision,
        "recall": recall,
        "f1_score": f1
    }
evaluation_results

{'stock market crash in asia': {'precision': 0.0,
  'recall': 0.0,
  'f1_score': 0.0},
 'covid vaccine rollout': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0.0},
 'elections in pakistan': {'precision': 0.0, 'recall': 0.0, 'f1_score': 0.0}}